source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

gem 'opal-haml'
gem 'hyalite'
gem 'menilite', github: 'youchan/menilite'

gem 'rake'
gem 'sqlite3'

gem 'haml'
gem 'sass'
